import { Garment } from './types';

export const INITIAL_GARMENTS: Garment[] = [
  {
    id: 'g-001',
    code: '001',
    name: 'GORE-TEX PRO 3L 重工防水冲锋衣',
    category: '上装',
    image: '/src/assets/images/cyber_techwear_jacket_1782367580311.jpg',
    status: 'Active',
    location: '1号挂架 / A-04分区',
    videoLogs: ['🎬 第3期漫剧', '🎬 第5期整蛊', '🎬 第12期机能指南'],
    materials: 'Nylon 100% (Gore-Tex Pro 三层压胶面料)',
    details: '配备 YKK AquaGuard 密合防水拉链，3D立体剪裁肘部关节，磁吸式快速开合防风风帽。',
    functionality: ['28,000mm强效防水', '极度防风', '透气耐磨', '模块化兜帽'],
    weight: '520g',
    createdAt: '2026-02-14',
  },
  {
    id: 'g-002',
    code: '002',
    name: 'M-65 模块化战术胸挂背心',
    category: '上装',
    image: '/src/assets/images/tactical_modular_vest_1782367594601.jpg',
    status: 'Active',
    location: '1号挂架 / B-01分区',
    videoLogs: ['🎬 第2期穿搭', '🎬 第5期整蛊', '🎬 第10期荒野生存'],
    materials: 'Cordura® 1000D 弹道尼龙 / 3D 蜂窝透气网格',
    details: '重型战术胸挂，配备激光切割 MOLLE 挂载系统、德国 Fidlock® 磁吸快开扣及双侧饮水管通道。',
    functionality: ['MOLLE系统扩充', '超强防磨', '高负重承托', 'Fidlock磁吸扣'],
    weight: '380g',
    createdAt: '2026-03-22',
  },
  {
    id: 'g-003',
    code: '003',
    name: '不对称多口袋战术工装裤',
    category: '下装',
    image: '/src/assets/images/cyberpunk_cargo_pants_1782367607427.jpg',
    status: 'Archived',
    location: '2号挂架 / C-02分区',
    videoLogs: ['🎬 第1期极限测评', '🎬 第3期漫剧'],
    materials: '棉涤耐磨抗撕裂格子布 (DWR防泼水涂层)',
    details: '设计有双向快取超大工装口袋、180度攀爬膝部裁片，脚踝部弹力抽绳抽褶可收紧裤脚。',
    functionality: ['高效防泼水', '十口袋收纳', '180°跨步剪裁', '双层耐磨膝盖'],
    weight: '640g',
    createdAt: '2026-01-10',
  },
  {
    id: 'g-004',
    code: '004',
    name: '暗黑系全天候中帮战术靴',
    category: '鞋子',
    image: '/src/assets/images/futuristic_boots_1782367619182.jpg',
    status: 'Active',
    location: '2号挂架 / D-02分区',
    videoLogs: ['🎬 第3期漫剧', '🎬 第7期雨林生存', '🎬 第15期暗黑鞋评'],
    materials: '哑光科技合成皮革 / Kevlar® 凯夫拉防刺护板',
    details: '高性能全天候鞋履，配备 Vibram® 黄金大底、Boa 双轴旋钮快速系带以及防水透气微孔内衬。',
    functionality: ['Vibram防滑大底', '凯夫拉防刺穿', 'Boa旋钮快速系带', '超强抗寒保暖'],
    weight: '820g',
    createdAt: '2026-04-05',
  },
  {
    id: 'g-005',
    code: '005',
    name: '模块化 X-Pac 防水轻量胸包',
    category: '已搭配好服装',
    image: '/src/assets/images/modular_sling_bag_1782367660673.jpg',
    status: 'Active',
    location: '安全箱柜 X / SLOT 09',
    videoLogs: ['🎬 第8期EDC翻包', '🎬 第12期机能指南'],
    materials: 'Dimension-Polyant® X-Pac VX21 / YKK AquaGuard防水拉链',
    details: '超轻量化全天候防水胸包，带三点式减负背带系统。集成平板电脑夹层，正面带磁吸挂件锁点。',
    functionality: ['X-Pac顶级防水', '三点减负背带', 'Fidlock秒开快扣', '多层多格网'],
    weight: '290g',
    createdAt: '2026-05-18',
  }
];

export const VIDEO_SHOW_OPTIONS = [
  '🎬 第1期极限测评',
  '🎬 第2期穿搭',
  '🎬 第3期漫剧',
  '🎬 第5期整蛊',
  '🎬 第7期雨林生存',
  '🎬 第8期EDC翻包',
  '🎬 第10期荒野生存',
  '🎬 第12期机能指南',
  '🎬 第15期暗黑鞋评'
];
